/*Complete work tasks following a defined procedure in support of general office activities and product and service delivery within Lead and Opportunity Management. */
package org.museframework.bian.leaandoppman.dto.cr;

import org.museframework.common.core.MetaDto;
import org.museframework.common.core.MetaField;

@MetaDto
public class LeadandOpportunityProcedure {
    /*Reference to the associated customer (can currently be a person or a company)*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object customerReference;

    /*Reference to the customer campaign generating the lead (if the opportunity is generated by a campaign)*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object customerCampaignReference;

    /*The type of campaign (e.g. cross-sell, up-sell, retention)*/
    @MetaField
    private String customerCampaignType;

    /*The version number of the campaign (used to track campaign impact)*/
    @MetaField
    private String customerCampaignVersionNumber;

    /*The type of product or service identified in the lead/opportunity*/
    @MetaField
    private String productandServiceType;

    /*Reference to a specific product instance if the lead is an up-sell to an existing product agreement*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object productInstanceReference;

    /*Employees involved in capturing the lead/opportunity*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object employeeBusinessUnitReference;

    /*Narrative/description of the opportunity if available*/
    @MetaField
    private String leadandOpportunityDescription;

    /*Date and time and the location the lead/opportunity was captured*/
    @MetaField
    private String dateTimeLocation;

    public void setCustomerReference(org.museframework.bian.classes.Object customerReference) {
        this.customerReference = customerReference;
    }

    public org.museframework.bian.classes.Object getCustomerReference() {
        return customerReference;
    }

    public void setCustomerCampaignReference(org.museframework.bian.classes.Object customerCampaignReference) {
        this.customerCampaignReference = customerCampaignReference;
    }

    public org.museframework.bian.classes.Object getCustomerCampaignReference() {
        return customerCampaignReference;
    }

    public void setCustomerCampaignType(String customerCampaignType) {
        this.customerCampaignType = customerCampaignType;
    }

    public String getCustomerCampaignType() {
        return customerCampaignType;
    }

    public void setCustomerCampaignVersionNumber(String customerCampaignVersionNumber) {
        this.customerCampaignVersionNumber = customerCampaignVersionNumber;
    }

    public String getCustomerCampaignVersionNumber() {
        return customerCampaignVersionNumber;
    }

    public void setProductandServiceType(String productandServiceType) {
        this.productandServiceType = productandServiceType;
    }

    public String getProductandServiceType() {
        return productandServiceType;
    }

    public void setProductInstanceReference(org.museframework.bian.classes.Object productInstanceReference) {
        this.productInstanceReference = productInstanceReference;
    }

    public org.museframework.bian.classes.Object getProductInstanceReference() {
        return productInstanceReference;
    }

    public void setEmployeeBusinessUnitReference(org.museframework.bian.classes.Object employeeBusinessUnitReference) {
        this.employeeBusinessUnitReference = employeeBusinessUnitReference;
    }

    public org.museframework.bian.classes.Object getEmployeeBusinessUnitReference() {
        return employeeBusinessUnitReference;
    }

    public void setLeadandOpportunityDescription(String leadandOpportunityDescription) {
        this.leadandOpportunityDescription = leadandOpportunityDescription;
    }

    public String getLeadandOpportunityDescription() {
        return leadandOpportunityDescription;
    }

    public void setDateTimeLocation(String dateTimeLocation) {
        this.dateTimeLocation = dateTimeLocation;
    }

    public String getDateTimeLocation() {
        return dateTimeLocation;
    }
}