/*Complete work tasks following a defined procedure in support of general office activities and product and service delivery within Prospect Campaign Execution. */
package org.museframework.bian.procamexe.dto.cr;

import org.museframework.common.core.MetaDto;
import org.museframework.common.core.MetaField;

//refer to BOClass org.museframework.bian.classes.ProspectCampaignProcedure
@MetaDto
public class ProspectCampaignProcedure {
    /*The type or category of prospect campaign (e.g. acquisition, product discount incentive)*/
    @MetaField(0)
    private String prospectCampaignType;

    /*A description of the campaign that clarifies the intended context/use of the campaign, the mechanisms employed and the intended/anticipated response/impact*/
    @MetaField(0)
    private String prospectCampaignDescription;

    /*Reference to the business unit responsible for the campaign execution*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object employeeBusinessUnitReference;

    /*Details of the deployment set-up/configuration of the campaign for reference*/
    @MetaField(0)
    private String prospectCampaignProcedureSet_up;

    /*The prospect campaign version number used in the event*/
    @MetaField(0)
    private String prospectCampaignProcedureVersionNumber;

    /*The campaign processing schedule, covering prospect list selection/verification, execution, follow-up and analysis activities. Note this can be an ongoing campaign where worksteps continue in parallel*/
    @MetaField(0)
    private String prospectCampaignSchedule;

    /*Inventory record of any consumables that are to be used in the execution of the campaign (e.g. brochures)*/
    @MetaField(0)
    private String prospectCampaignConsumablesInventory;

    /*The type of consumable item associated with the campaign (e.g. gift, brochure)*/
    @MetaField(0)
    private String prospectCampaignConsumableType;

    /*The tracked inventory of the consumable item*/
    @MetaField(0)
    private String prospectCampaignConsumableHolding;

    /*Key dates associated with the campaign process (e.g. initiation date, version revision date, completion date)*/
    @MetaField(0)
    private String dateType;

    /*Value of the date type*/
    @MetaField(0)
    private String date;

    /*The result/impact of the overall prospect campaign event (that can include multiple identified prospects for on-boarding)*/
    @MetaField(0)
    private String prospectCampaignProcedureResult;

    /*A reference to prospects generated by the prospect campaign*/
    @MetaField(0)
    private String prospectCampaignProcedureProspectIdentification;

    /*Reference to the prospect on-boarding task as handled by the Party Lifecycle Management Service Domain*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object partyLifecycleManagementProcedureInstanceReference;

    public void setProspectCampaignType(String prospectCampaignType) {
        this.prospectCampaignType = prospectCampaignType;
    }

    public String getProspectCampaignType() {
        return prospectCampaignType;
    }

    public void setProspectCampaignDescription(String prospectCampaignDescription) {
        this.prospectCampaignDescription = prospectCampaignDescription;
    }

    public String getProspectCampaignDescription() {
        return prospectCampaignDescription;
    }

    public void setEmployeeBusinessUnitReference(org.museframework.bian.classes.Object employeeBusinessUnitReference) {
        this.employeeBusinessUnitReference = employeeBusinessUnitReference;
    }

    public org.museframework.bian.classes.Object getEmployeeBusinessUnitReference() {
        return employeeBusinessUnitReference;
    }

    public void setProspectCampaignProcedureSet_up(String prospectCampaignProcedureSet_up) {
        this.prospectCampaignProcedureSet_up = prospectCampaignProcedureSet_up;
    }

    public String getProspectCampaignProcedureSet_up() {
        return prospectCampaignProcedureSet_up;
    }

    public void setProspectCampaignProcedureVersionNumber(String prospectCampaignProcedureVersionNumber) {
        this.prospectCampaignProcedureVersionNumber = prospectCampaignProcedureVersionNumber;
    }

    public String getProspectCampaignProcedureVersionNumber() {
        return prospectCampaignProcedureVersionNumber;
    }

    public void setProspectCampaignSchedule(String prospectCampaignSchedule) {
        this.prospectCampaignSchedule = prospectCampaignSchedule;
    }

    public String getProspectCampaignSchedule() {
        return prospectCampaignSchedule;
    }

    public void setProspectCampaignConsumablesInventory(String prospectCampaignConsumablesInventory) {
        this.prospectCampaignConsumablesInventory = prospectCampaignConsumablesInventory;
    }

    public String getProspectCampaignConsumablesInventory() {
        return prospectCampaignConsumablesInventory;
    }

    public void setProspectCampaignConsumableType(String prospectCampaignConsumableType) {
        this.prospectCampaignConsumableType = prospectCampaignConsumableType;
    }

    public String getProspectCampaignConsumableType() {
        return prospectCampaignConsumableType;
    }

    public void setProspectCampaignConsumableHolding(String prospectCampaignConsumableHolding) {
        this.prospectCampaignConsumableHolding = prospectCampaignConsumableHolding;
    }

    public String getProspectCampaignConsumableHolding() {
        return prospectCampaignConsumableHolding;
    }

    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    public String getDateType() {
        return dateType;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }

    public void setProspectCampaignProcedureResult(String prospectCampaignProcedureResult) {
        this.prospectCampaignProcedureResult = prospectCampaignProcedureResult;
    }

    public String getProspectCampaignProcedureResult() {
        return prospectCampaignProcedureResult;
    }

    public void setProspectCampaignProcedureProspectIdentification(String prospectCampaignProcedureProspectIdentification) {
        this.prospectCampaignProcedureProspectIdentification = prospectCampaignProcedureProspectIdentification;
    }

    public String getProspectCampaignProcedureProspectIdentification() {
        return prospectCampaignProcedureProspectIdentification;
    }

    public void setPartyLifecycleManagementProcedureInstanceReference(org.museframework.bian.classes.Object partyLifecycleManagementProcedureInstanceReference) {
        this.partyLifecycleManagementProcedureInstanceReference = partyLifecycleManagementProcedureInstanceReference;
    }

    public org.museframework.bian.classes.Object getPartyLifecycleManagementProcedureInstanceReference() {
        return partyLifecycleManagementProcedureInstanceReference;
    }
}