/*A collection of goals and objectives for the enterprise and its main divisions

Example: Increase marketshare*/
package org.museframework.bian.businessdevelopment.dto.bq;

public class Initiative {
    /*Business unit responsible for implementing a specific initiative supporting the business development strategy*/
    private org.museframework.bian.classes.Object businessDevelopmentInitiativeBusinessUnitReference;

    /*The type of initiative (e.g. development project, acquisition, campaign, media communications)*/
    private String businessDevelopmentInitiativeType;

    /*Definition of the initiative, including planned actions, deliverables and intended outcomes*/
    private String businessDevelopmentInitiativeDescription;

    /*Planned and actual dates for activities making up the initiative. Any necessary details describing the purpose or reference properties of the transaction*/
    private String businessDevelopmentInitiativeSchedule;

    /*File of consolidated notes, assessments etc. arising from the work*/
    private String businessDevelopmentInitiativeWorkProducts;

    /*An assessment of the results/impact of the business development initiative*/
    private String businessDevelopmentInitiativeResult;

    /*Reference to associated documents (when appropriate)*/
    private org.museframework.bian.classes.Object documentDirectoryEntryInstanceReference;

    /*Reference to the correspondence generated by the initiative*/
    private org.museframework.bian.classes.Object correspondenceInstanceReference;

    /*Key dates and times associated with the execution of the business development initiative (e.g. start, review, completion)*/
    private String dateType;

    /*Value of the date type*/
    private String date;

    public void setBusinessDevelopmentInitiativeBusinessUnitReference(org.museframework.bian.classes.Object businessDevelopmentInitiativeBusinessUnitReference) {
        this.businessDevelopmentInitiativeBusinessUnitReference = businessDevelopmentInitiativeBusinessUnitReference;
    }

    public org.museframework.bian.classes.Object getBusinessDevelopmentInitiativeBusinessUnitReference() {
        return businessDevelopmentInitiativeBusinessUnitReference;
    }

    public void setBusinessDevelopmentInitiativeType(String businessDevelopmentInitiativeType) {
        this.businessDevelopmentInitiativeType = businessDevelopmentInitiativeType;
    }

    public String getBusinessDevelopmentInitiativeType() {
        return businessDevelopmentInitiativeType;
    }

    public void setBusinessDevelopmentInitiativeDescription(String businessDevelopmentInitiativeDescription) {
        this.businessDevelopmentInitiativeDescription = businessDevelopmentInitiativeDescription;
    }

    public String getBusinessDevelopmentInitiativeDescription() {
        return businessDevelopmentInitiativeDescription;
    }

    public void setBusinessDevelopmentInitiativeSchedule(String businessDevelopmentInitiativeSchedule) {
        this.businessDevelopmentInitiativeSchedule = businessDevelopmentInitiativeSchedule;
    }

    public String getBusinessDevelopmentInitiativeSchedule() {
        return businessDevelopmentInitiativeSchedule;
    }

    public void setBusinessDevelopmentInitiativeWorkProducts(String businessDevelopmentInitiativeWorkProducts) {
        this.businessDevelopmentInitiativeWorkProducts = businessDevelopmentInitiativeWorkProducts;
    }

    public String getBusinessDevelopmentInitiativeWorkProducts() {
        return businessDevelopmentInitiativeWorkProducts;
    }

    public void setBusinessDevelopmentInitiativeResult(String businessDevelopmentInitiativeResult) {
        this.businessDevelopmentInitiativeResult = businessDevelopmentInitiativeResult;
    }

    public String getBusinessDevelopmentInitiativeResult() {
        return businessDevelopmentInitiativeResult;
    }

    public void setDocumentDirectoryEntryInstanceReference(org.museframework.bian.classes.Object documentDirectoryEntryInstanceReference) {
        this.documentDirectoryEntryInstanceReference = documentDirectoryEntryInstanceReference;
    }

    public org.museframework.bian.classes.Object getDocumentDirectoryEntryInstanceReference() {
        return documentDirectoryEntryInstanceReference;
    }

    public void setCorrespondenceInstanceReference(org.museframework.bian.classes.Object correspondenceInstanceReference) {
        this.correspondenceInstanceReference = correspondenceInstanceReference;
    }

    public org.museframework.bian.classes.Object getCorrespondenceInstanceReference() {
        return correspondenceInstanceReference;
    }

    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    public String getDateType() {
        return dateType;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }
}