/*Complete work tasks following a defined procedure in support of general office activities and product and service delivery within Customer Campaign Execution. */
package org.museframework.bian.cuscamexe.dto.cr;

public class CustomerCampaignProcedure extends org.museframework.bian.classes.CustomerCampaignProcedure {
    /*The type or category of customer campaign (e.g. cross-sell, up-sell, retention)*/
    private String customerCampaignType;

    /*A description of the campaign that clarifies the intended context/use of the campaign, the mechanisms employed and the intended/anticipated response/impact*/
    private String customerCampaignDescription;

    /*Reference to the business unit responsible for the campaign execution*/
    private org.museframework.bian.classes.Object employeeBusinessUnitReference;

    /*Details of the deployment set-up/configuration of the campaign for reference*/
    private String customerCampaignProcedureSet_up;

    /*The customer campaign version number used in the event*/
    private String customerCampaignProcedureVersionNumber;

    /*The campaign processing schedule, covering candidate selection, execution, flow-up and analysis activities. Note this can be an ongoing campaign where worksteps continue in parallel*/
    private String customerCampaignSchedule;

    /*Inventory record of any consumables that are to be used in the execution of the campaign (e.g. brochures)*/
    private String customerCampaignConsumablesInventory;

    /*The type of consumable item associated with the campaign (e.g. gift, brochure)*/
    private String customerCampaignConsumableType;

    /*The tracked inventory of the consumable item*/
    private String customerCampaignConsumableHolding;

    /*Key dates associated with the campaign process (e.g. initiation date, version revision date, completion date)*/
    private String dateType;

    /*Value of the date type*/
    private String date;

    /*The result/impact of the overall customer campaign event (that can include multiple identified leads/opportunities)*/
    private String customerCampaignProcedureResult;

    /*A description of leads and opportunities generated by the customer campaign*/
    private String customerCampaignProcedureLeadandOpportunityDescription;

    /*Reference to the lead/opportunity as handled by the Lead/Opportunity Management Service Domain*/
    private org.museframework.bian.classes.Object leadandOpportunityProcedureInstanceReference;

    public void setCustomerCampaignType(String customerCampaignType) {
        this.customerCampaignType = customerCampaignType;
    }

    public String getCustomerCampaignType() {
        return customerCampaignType;
    }

    public void setCustomerCampaignDescription(String customerCampaignDescription) {
        this.customerCampaignDescription = customerCampaignDescription;
    }

    public String getCustomerCampaignDescription() {
        return customerCampaignDescription;
    }

    public void setEmployeeBusinessUnitReference(org.museframework.bian.classes.Object employeeBusinessUnitReference) {
        this.employeeBusinessUnitReference = employeeBusinessUnitReference;
    }

    public org.museframework.bian.classes.Object getEmployeeBusinessUnitReference() {
        return employeeBusinessUnitReference;
    }

    public void setCustomerCampaignProcedureSet_up(String customerCampaignProcedureSet_up) {
        this.customerCampaignProcedureSet_up = customerCampaignProcedureSet_up;
    }

    public String getCustomerCampaignProcedureSet_up() {
        return customerCampaignProcedureSet_up;
    }

    public void setCustomerCampaignProcedureVersionNumber(String customerCampaignProcedureVersionNumber) {
        this.customerCampaignProcedureVersionNumber = customerCampaignProcedureVersionNumber;
    }

    public String getCustomerCampaignProcedureVersionNumber() {
        return customerCampaignProcedureVersionNumber;
    }

    public void setCustomerCampaignSchedule(String customerCampaignSchedule) {
        this.customerCampaignSchedule = customerCampaignSchedule;
    }

    public String getCustomerCampaignSchedule() {
        return customerCampaignSchedule;
    }

    public void setCustomerCampaignConsumablesInventory(String customerCampaignConsumablesInventory) {
        this.customerCampaignConsumablesInventory = customerCampaignConsumablesInventory;
    }

    public String getCustomerCampaignConsumablesInventory() {
        return customerCampaignConsumablesInventory;
    }

    public void setCustomerCampaignConsumableType(String customerCampaignConsumableType) {
        this.customerCampaignConsumableType = customerCampaignConsumableType;
    }

    public String getCustomerCampaignConsumableType() {
        return customerCampaignConsumableType;
    }

    public void setCustomerCampaignConsumableHolding(String customerCampaignConsumableHolding) {
        this.customerCampaignConsumableHolding = customerCampaignConsumableHolding;
    }

    public String getCustomerCampaignConsumableHolding() {
        return customerCampaignConsumableHolding;
    }

    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    public String getDateType() {
        return dateType;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }

    public void setCustomerCampaignProcedureResult(String customerCampaignProcedureResult) {
        this.customerCampaignProcedureResult = customerCampaignProcedureResult;
    }

    public String getCustomerCampaignProcedureResult() {
        return customerCampaignProcedureResult;
    }

    public void setCustomerCampaignProcedureLeadandOpportunityDescription(String customerCampaignProcedureLeadandOpportunityDescription) {
        this.customerCampaignProcedureLeadandOpportunityDescription = customerCampaignProcedureLeadandOpportunityDescription;
    }

    public String getCustomerCampaignProcedureLeadandOpportunityDescription() {
        return customerCampaignProcedureLeadandOpportunityDescription;
    }

    public void setLeadandOpportunityProcedureInstanceReference(org.museframework.bian.classes.Object leadandOpportunityProcedureInstanceReference) {
        this.leadandOpportunityProcedureInstanceReference = leadandOpportunityProcedureInstanceReference;
    }

    public org.museframework.bian.classes.Object getLeadandOpportunityProcedureInstanceReference() {
        return leadandOpportunityProcedureInstanceReference;
    }
}