/*To test or assess an entity, possibly against some formal qualification or certification requirement within Suitability Checking. */
package org.museframework.bian.suitabilitychecking.dto.cr;

import org.museframework.common.core.MetaDto;
import org.museframework.common.core.MetaField;

//refer to BOClass org.museframework.bian.classes.SuitabilityAssessment
@MetaDto
public class SuitabilityAssessment {
    /*Business unit submitting the proposed transaction for review*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object employeeBusinessUnitReference;

    /*Reference to the customer related to the proposed transaction*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object customerReference;

    /*The type of market order (e.g. Day Order. Order on Open/Close, Fill or Kill, Limit Order)*/
    @MetaField(0)
    private String marketOrderType;

    /*Reference to the associated investment portfolio record of all holdings (referenced to check securities availability if necessary)*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object investmentPortfolioInstanceReference;

    /*Any customer specific processing preferences or requirements*/
    @MetaField(0)
    private String customerMarketOrderProcessingInstruction;

    /*The details of the market order transaction that is to undergo suitability checks*/
    @MetaField(0)
    private String proposedMarketOrderTransaction;

    /*Reference to the underlying cash account supporting the transaction*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object investmentAccountArrangementInstanceReference;

    /*The security to be traded*/
    @MetaField(0)
    private String securityType;

    /*The volume of shares to be bought or sold*/
    @MetaField(0)
    private String amount;

    /*Key dates associated with the proposed transaction (e.g. opportunity identification, proposal/pitch, suitability evaluation initiated)*/
    @MetaField(0)
    private String dateType;

    /*Value of the specific date type*/
    @MetaField(0)
    private String date;

    /*The type and make-up of suitability compliance tests referenced in the assessment*/
    @MetaField(0)
    private String suitabilityAssessmentType;

    /*The document reference for any documents accessed and generated (e.g. disclosures)*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object documentDirectoryEntryInstanceReference;

    /*Reference to any correspondence generated by the suitability check*/
    @MetaField(ref=true)
    private org.museframework.bian.classes.Object correspondenceInstanceReference;

    /*Work documentation, forms and schedules produced and referenced during the assessment*/
    @MetaField(0)
    private String suitabilityComplianceAssessmentWorkProducts;

    /*Outcome/result of the suitability assessment, can include reported details if appropriate*/
    @MetaField(0)
    private String suitabilityComplianceAssessmentResult;

    public void setEmployeeBusinessUnitReference(org.museframework.bian.classes.Object employeeBusinessUnitReference) {
        this.employeeBusinessUnitReference = employeeBusinessUnitReference;
    }

    public org.museframework.bian.classes.Object getEmployeeBusinessUnitReference() {
        return employeeBusinessUnitReference;
    }

    public void setCustomerReference(org.museframework.bian.classes.Object customerReference) {
        this.customerReference = customerReference;
    }

    public org.museframework.bian.classes.Object getCustomerReference() {
        return customerReference;
    }

    public void setMarketOrderType(String marketOrderType) {
        this.marketOrderType = marketOrderType;
    }

    public String getMarketOrderType() {
        return marketOrderType;
    }

    public void setInvestmentPortfolioInstanceReference(org.museframework.bian.classes.Object investmentPortfolioInstanceReference) {
        this.investmentPortfolioInstanceReference = investmentPortfolioInstanceReference;
    }

    public org.museframework.bian.classes.Object getInvestmentPortfolioInstanceReference() {
        return investmentPortfolioInstanceReference;
    }

    public void setCustomerMarketOrderProcessingInstruction(String customerMarketOrderProcessingInstruction) {
        this.customerMarketOrderProcessingInstruction = customerMarketOrderProcessingInstruction;
    }

    public String getCustomerMarketOrderProcessingInstruction() {
        return customerMarketOrderProcessingInstruction;
    }

    public void setProposedMarketOrderTransaction(String proposedMarketOrderTransaction) {
        this.proposedMarketOrderTransaction = proposedMarketOrderTransaction;
    }

    public String getProposedMarketOrderTransaction() {
        return proposedMarketOrderTransaction;
    }

    public void setInvestmentAccountArrangementInstanceReference(org.museframework.bian.classes.Object investmentAccountArrangementInstanceReference) {
        this.investmentAccountArrangementInstanceReference = investmentAccountArrangementInstanceReference;
    }

    public org.museframework.bian.classes.Object getInvestmentAccountArrangementInstanceReference() {
        return investmentAccountArrangementInstanceReference;
    }

    public void setSecurityType(String securityType) {
        this.securityType = securityType;
    }

    public String getSecurityType() {
        return securityType;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getAmount() {
        return amount;
    }

    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    public String getDateType() {
        return dateType;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }

    public void setSuitabilityAssessmentType(String suitabilityAssessmentType) {
        this.suitabilityAssessmentType = suitabilityAssessmentType;
    }

    public String getSuitabilityAssessmentType() {
        return suitabilityAssessmentType;
    }

    public void setDocumentDirectoryEntryInstanceReference(org.museframework.bian.classes.Object documentDirectoryEntryInstanceReference) {
        this.documentDirectoryEntryInstanceReference = documentDirectoryEntryInstanceReference;
    }

    public org.museframework.bian.classes.Object getDocumentDirectoryEntryInstanceReference() {
        return documentDirectoryEntryInstanceReference;
    }

    public void setCorrespondenceInstanceReference(org.museframework.bian.classes.Object correspondenceInstanceReference) {
        this.correspondenceInstanceReference = correspondenceInstanceReference;
    }

    public org.museframework.bian.classes.Object getCorrespondenceInstanceReference() {
        return correspondenceInstanceReference;
    }

    public void setSuitabilityComplianceAssessmentWorkProducts(String suitabilityComplianceAssessmentWorkProducts) {
        this.suitabilityComplianceAssessmentWorkProducts = suitabilityComplianceAssessmentWorkProducts;
    }

    public String getSuitabilityComplianceAssessmentWorkProducts() {
        return suitabilityComplianceAssessmentWorkProducts;
    }

    public void setSuitabilityComplianceAssessmentResult(String suitabilityComplianceAssessmentResult) {
        this.suitabilityComplianceAssessmentResult = suitabilityComplianceAssessmentResult;
    }

    public String getSuitabilityComplianceAssessmentResult() {
        return suitabilityComplianceAssessmentResult;
    }
}