/*A payment Instruction generated by the fulfilment of a Standing Order Arrangement */
package org.museframework.bian.classes;

import org.museframework.common.core.EmptyBianClass;

@EmptyBianClass
public class StandingOrderInstruction {
}