/*A collection of goals and objectives for the enterprise and its main divisions

Example: Increase marketshare*/
package org.museframework.bian.segmentdirection.dto.bq;

public class Initiative {
    /*Business unit responsible for implementing a specific initiative supporting the segment strategy*/
    private org.museframework.bian.classes.Object segmentInitiativeBusinessUnitReference;

    /*The type of initiative (e.g. development project, acquisition, campaign, media communications)*/
    private String segmentInitiativeType;

    /*Definition of the initiative, including planned actions, deliverables and intended outcomes*/
    private String segmentInitiativeDescription;

    /*Planned and actual dates for activities making up the initiative. Any necessary details describing the purpose or reference properties of the transaction*/
    private String segmentInitiativeSchedule;

    /*File of consolidated notes, assessments etc. arising from the work*/
    private String segmentInitiativeWorkProducts;

    /*An assessment of the results/impact of the segment initiative*/
    private String segmentInitiativeResult;

    /*Reference to associated documents (when appropriate)*/
    private org.museframework.bian.classes.Object documentDirectoryEntryInstanceReference;

    /*Reference to the correspondence generated by the initiative*/
    private org.museframework.bian.classes.Object correspondenceInstanceReference;

    /*Key dates and times associated with the execution of the segment initiative (e.g. start, review, completion)*/
    private String dateType;

    /*Value of the date type*/
    private String date;

    public void setSegmentInitiativeBusinessUnitReference(org.museframework.bian.classes.Object segmentInitiativeBusinessUnitReference) {
        this.segmentInitiativeBusinessUnitReference = segmentInitiativeBusinessUnitReference;
    }

    public org.museframework.bian.classes.Object getSegmentInitiativeBusinessUnitReference() {
        return segmentInitiativeBusinessUnitReference;
    }

    public void setSegmentInitiativeType(String segmentInitiativeType) {
        this.segmentInitiativeType = segmentInitiativeType;
    }

    public String getSegmentInitiativeType() {
        return segmentInitiativeType;
    }

    public void setSegmentInitiativeDescription(String segmentInitiativeDescription) {
        this.segmentInitiativeDescription = segmentInitiativeDescription;
    }

    public String getSegmentInitiativeDescription() {
        return segmentInitiativeDescription;
    }

    public void setSegmentInitiativeSchedule(String segmentInitiativeSchedule) {
        this.segmentInitiativeSchedule = segmentInitiativeSchedule;
    }

    public String getSegmentInitiativeSchedule() {
        return segmentInitiativeSchedule;
    }

    public void setSegmentInitiativeWorkProducts(String segmentInitiativeWorkProducts) {
        this.segmentInitiativeWorkProducts = segmentInitiativeWorkProducts;
    }

    public String getSegmentInitiativeWorkProducts() {
        return segmentInitiativeWorkProducts;
    }

    public void setSegmentInitiativeResult(String segmentInitiativeResult) {
        this.segmentInitiativeResult = segmentInitiativeResult;
    }

    public String getSegmentInitiativeResult() {
        return segmentInitiativeResult;
    }

    public void setDocumentDirectoryEntryInstanceReference(org.museframework.bian.classes.Object documentDirectoryEntryInstanceReference) {
        this.documentDirectoryEntryInstanceReference = documentDirectoryEntryInstanceReference;
    }

    public org.museframework.bian.classes.Object getDocumentDirectoryEntryInstanceReference() {
        return documentDirectoryEntryInstanceReference;
    }

    public void setCorrespondenceInstanceReference(org.museframework.bian.classes.Object correspondenceInstanceReference) {
        this.correspondenceInstanceReference = correspondenceInstanceReference;
    }

    public org.museframework.bian.classes.Object getCorrespondenceInstanceReference() {
        return correspondenceInstanceReference;
    }

    public void setDateType(String dateType) {
        this.dateType = dateType;
    }

    public String getDateType() {
        return dateType;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDate() {
        return date;
    }
}